# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabLoggerGlobals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.TextField()),
                ('exp', models.TextField()),
                ('instance', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Saving date')),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabLoggerGlobalValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('int_value', models.TextField(null=True)),
                ('float_value', models.FloatField(null=True)),
                ('text_value', models.TextField(null=True)),
                ('bool_value', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.LabLoggerGlobals')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabLoggerLocals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.TextField()),
                ('exp', models.TextField()),
                ('instance', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Saving date')),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabLoggerLocalValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('int_value', models.TextField(null=True)),
                ('float_value', models.FloatField(null=True)),
                ('text_value', models.TextField(null=True)),
                ('bool_value', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.LabLoggerLocals')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabLoggerParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.TextField()),
                ('exp', models.TextField()),
                ('instance', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Saving date')),
                ('param', models.TextField()),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabLoggerParamValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('int_value', models.TextField(null=True)),
                ('float_value', models.FloatField(null=True)),
                ('text_value', models.TextField(null=True)),
                ('bool_value', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabLoggerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.TextField()),
                ('exp', models.TextField()),
                ('instance', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Saving date')),
                ('result', models.TextField()),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabLoggerTraceback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.TextField()),
                ('exp', models.TextField()),
                ('instance', models.BigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Saving date')),
                ('exec_info', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabLoggerTracebackValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('int_value', models.TextField(null=True)),
                ('float_value', models.FloatField(null=True)),
                ('text_value', models.TextField(null=True)),
                ('bool_value', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.LabLoggerTraceback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='labloggerparamvalue',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.LabLoggerResult'),
        ),
    ]
