# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='labloggerglobals',
            table='globals',
        ),
        migrations.AlterModelTable(
            name='labloggerglobalvalue',
            table='global_values',
        ),
        migrations.AlterModelTable(
            name='labloggerlocals',
            table='vars',
        ),
        migrations.AlterModelTable(
            name='labloggerlocalvalue',
            table='local_values',
        ),
        migrations.AlterModelTable(
            name='labloggerparam',
            table='param',
        ),
        migrations.AlterModelTable(
            name='labloggerparamvalue',
            table='param_values',
        ),
        migrations.AlterModelTable(
            name='labloggerresult',
            table='result',
        ),
        migrations.AlterModelTable(
            name='labloggertraceback',
            table='traceback',
        ),
        migrations.AlterModelTable(
            name='labloggertracebackvalue',
            table='traceback_values',
        ),
    ]
