# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20170531_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labloggerglobalvalue',
            old_name='source',
            new_name='globals',
        ),
        migrations.RenameField(
            model_name='labloggerlocalvalue',
            old_name='source',
            new_name='vars',
        ),
        migrations.RenameField(
            model_name='labloggerparamvalue',
            old_name='source',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='labloggertracebackvalue',
            old_name='source',
            new_name='traceback',
        ),
    ]
